//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaCodeWhite.Shared.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaCodeWhite.Shared.Localisation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Block.
        /// </summary>
        public static string AccessBlock {
            get {
                return ResourceManager.GetString("AccessBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add your message below.
        /// </summary>
        public static string AddYourMessageBelow {
            get {
                return ResourceManager.GetString("AddYourMessageBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber.
        /// </summary>
        public static string Amber {
            get {
                return ResourceManager.GetString("Amber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambulance.
        /// </summary>
        public static string Ambulance {
            get {
                return ResourceManager.GetString("Ambulance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambulance Clearance (last 3hrs).
        /// </summary>
        public static string AmbulanceClearanceLast3Hrs {
            get {
                return ResourceManager.GetString("AmbulanceClearanceLast3Hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambulance Service.
        /// </summary>
        public static string AmbulanceService {
            get {
                return ResourceManager.GetString("AmbulanceService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributions.
        /// </summary>
        public static string Attributions {
            get {
                return ResourceManager.GetString("Attributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Time.
        /// </summary>
        public static string AvgTime {
            get {
                return ResourceManager.GetString("AvgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Wait Time.
        /// </summary>
        public static string AvgWaitTime {
            get {
                return ResourceManager.GetString("AvgWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on or contains data provided by the Government of South Australia (Department for Health and Wellbeing). Copyright of the Government of South Australia..
        /// </summary>
        public static string BasedOnDataProvidedSa {
            get {
                return ResourceManager.GetString("BasedOnDataProvidedSa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BURN.
        /// </summary>
        public static string BurnCode {
            get {
                return ResourceManager.GetString("BurnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burn.
        /// </summary>
        public static string BurnName {
            get {
                return ResourceManager.GetString("BurnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string Busy {
            get {
                return ResourceManager.GetString("Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCU.
        /// </summary>
        public static string CcuCode {
            get {
                return ResourceManager.GetString("CcuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronary Care.
        /// </summary>
        public static string CcuName {
            get {
                return ResourceManager.GetString("CcuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared.
        /// </summary>
        public static string Cleared {
            get {
                return ResourceManager.GetString("Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code White.
        /// </summary>
        public static string CodeWhite {
            get {
                return ResourceManager.GetString("CodeWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commenced Treatment.
        /// </summary>
        public static string CommencedTreatment {
            get {
                return ResourceManager.GetString("CommencedTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you rely on the information from this app you are responsible for ensuring by independent verification its accuracy, currency or completeness..
        /// </summary>
        public static string DisclaimerResponsibleForAccuracy {
            get {
                return ResourceManager.GetString("DisclaimerResponsibleForAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of the information and data contained within this app is at your sole risk..
        /// </summary>
        public static string DisclaimerUseOfInformation {
            get {
                return ResourceManager.GetString("DisclaimerUseOfInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ED.
        /// </summary>
        public static string ED {
            get {
                return ResourceManager.GetString("ED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email outtaapps@gmail.com directly..
        /// </summary>
        public static string EmailDirectly {
            get {
                return ResourceManager.GetString("EmailDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Department.
        /// </summary>
        public static string EmergencyDepartment {
            get {
                return ResourceManager.GetString("EmergencyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp. Arrivals.
        /// </summary>
        public static string ExpArrivals {
            get {
                return ResourceManager.GetString("ExpArrivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Arrivals.
        /// </summary>
        public static string ExpectedArrivals {
            get {
                return ResourceManager.GetString("ExpectedArrivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeWhite - Feedback ({0}).
        /// </summary>
        public static string FeedbackSubjectItem {
            get {
                return ResourceManager.GetString("FeedbackSubjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 30mins.
        /// </summary>
        public static string GreaterThan30Mins {
            get {
                return ResourceManager.GetString("GreaterThan30Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Code.
        /// </summary>
        public static string HospitalCode {
            get {
                return ResourceManager.GetString("HospitalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICU.
        /// </summary>
        public static string IcuCode {
            get {
                return ResourceManager.GetString("IcuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensive Care.
        /// </summary>
        public static string IcuName {
            get {
                return ResourceManager.GetString("IcuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inpatient Bed Status.
        /// </summary>
        public static string InpatientBedStatus {
            get {
                return ResourceManager.GetString("InpatientBedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inpatients waiting for a bed.
        /// </summary>
        public static string InpatientsWaitingForBed {
            get {
                return ResourceManager.GetString("InpatientsWaitingForBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},.
        /// </summary>
        public static string ItemComma {
            get {
                return ResourceManager.GetString("ItemComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string ItemCommaItem {
            get {
                return ResourceManager.GetString("ItemCommaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string ItemDashItem {
            get {
                return ResourceManager.GetString("ItemDashItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h.
        /// </summary>
        public static string ItemH {
            get {
                return ResourceManager.GetString("ItemH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}hr.
        /// </summary>
        public static string ItemHr {
            get {
                return ResourceManager.GetString("ItemHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}hrs.
        /// </summary>
        public static string ItemHrs {
            get {
                return ResourceManager.GetString("ItemHrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}m.
        /// </summary>
        public static string ItemM {
            get {
                return ResourceManager.GetString("ItemM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}min.
        /// </summary>
        public static string ItemMin {
            get {
                return ResourceManager.GetString("ItemMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}mins.
        /// </summary>
        public static string ItemMins {
            get {
                return ResourceManager.GetString("ItemMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string ItemOfItem {
            get {
                return ResourceManager.GetString("ItemOfItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string ItemParenthesesItem {
            get {
                return ResourceManager.GetString("ItemParenthesesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.##}%.
        /// </summary>
        public static string ItemPercent {
            get {
                return ResourceManager.GetString("ItemPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resus.
        /// </summary>
        public static string ItemResus {
            get {
                return ResourceManager.GetString("ItemResus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        public static string ItemSlashItem {
            get {
                return ResourceManager.GetString("ItemSlashItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string ItemSpaceItem {
            get {
                return ResourceManager.GetString("ItemSpaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} total.
        /// </summary>
        public static string ItemTotal {
            get {
                return ResourceManager.GetString("ItemTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MH.
        /// </summary>
        public static string MhCode {
            get {
                return ResourceManager.GetString("MhCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental Health.
        /// </summary>
        public static string MhName {
            get {
                return ResourceManager.GetString("MhName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEO.
        /// </summary>
        public static string NeoCode {
            get {
                return ResourceManager.GetString("NeoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neonatal.
        /// </summary>
        public static string NeoName {
            get {
                return ResourceManager.GetString("NeoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notifications for when a hospital&apos;s emergency department alert status changes to white..
        /// </summary>
        public static string NotificationsDescription {
            get {
                return ResourceManager.GetString("NotificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBST.
        /// </summary>
        public static string ObstCode {
            get {
                return ResourceManager.GetString("ObstCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstetric.
        /// </summary>
        public static string ObstName {
            get {
                return ResourceManager.GetString("ObstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy.
        /// </summary>
        public static string Occupancy {
            get {
                return ResourceManager.GetString("Occupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of total capacity.
        /// </summary>
        public static string OfTotalCapacity {
            get {
                return ResourceManager.GetString("OfTotalCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open App Settings.
        /// </summary>
        public static string OpenAppSettings {
            get {
                return ResourceManager.GetString("OpenAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAED.
        /// </summary>
        public static string PaedCode {
            get {
                return ResourceManager.GetString("PaedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paediatric.
        /// </summary>
        public static string PaedName {
            get {
                return ResourceManager.GetString("PaedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Rate SA CodeWhite.
        /// </summary>
        public static string PleaseRateCw {
            get {
                return ResourceManager.GetString("PleaseRateCw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuscitation.
        /// </summary>
        public static string Resuscitation {
            get {
                return ResourceManager.GetString("Resuscitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA CodeWhite.
        /// </summary>
        public static string SaCodeWhite {
            get {
                return ResourceManager.GetString("SaCodeWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA Health.
        /// </summary>
        public static string SAHealth {
            get {
                return ResourceManager.GetString("SAHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty Beds.
        /// </summary>
        public static string SpecialtyBeds {
            get {
                return ResourceManager.GetString("SpecialtyBeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treating.
        /// </summary>
        public static string Treating {
            get {
                return ResourceManager.GetString("Treating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Send Email.
        /// </summary>
        public static string UnableToSendEmail {
            get {
                return ResourceManager.GetString("UnableToSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Busy.
        /// </summary>
        public static string VeryBusy {
            get {
                return ResourceManager.GetString("VeryBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for bed.
        /// </summary>
        public static string WaitingForBed {
            get {
                return ResourceManager.GetString("WaitingForBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Times.
        /// </summary>
        public static string WaitingTimes {
            get {
                return ResourceManager.GetString("WaitingTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to be Seen.
        /// </summary>
        public static string WaitingToBeSeen {
            get {
                return ResourceManager.GetString("WaitingToBeSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
